### ISSUE TITLE
Please grade my homework, @adwasser !

### ISSUE THREAD

**Issue by pwillits** [pwillits/astr-119-hw-1#1]
Thanks!

**Comment by adwasser** [comment]
@pwillits , for future assignments, please mention me (i.e., typing `@adwasser`) in the body of the issue, since I don't see it if you type it in the title.  Thanks!

**Comment by pwillits** [comment]
Ok, will do!

Peter

**Comment by pwillits** [comment]
removed extra x = 9 's . closes #1
